name: "Workflow to deploy Terraform based infra "

run-name: "TF ${{ inputs.target_env }}"

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select Environment (uat, sit, production, drhub)"
        required: true
        type: choice
        options: [uat, sit, production, drhub]

      working_directory:
        description: "Terraform config directory path."
        required: true
        default: "."
        
      selected_branch:
        description: "Git branch to deploy from"
        required: true
        default: "main"

      change_ref:
        description: "Change or ticket reference"
        required: true
        default: "manual"

      change_reason:
        description: "Reason for change"
        required: true
        default: "standard-deployment"

      rollback_plan:
        description: "Rollback strategy"
        required: true
        default: "reapply-previous-state"   


permissions:
  contents: read
  id-token: write

concurrency:
  group: "tf-${{ inputs.target_env }}-${{ inputs.working_directory }}"
  cancel-in-progress: false

jobs:
  preflight:
    name: "Preflight"
    uses: ./.github/workflows/preflight_checks.yml

    with:
      target_env: ${{ inputs.target_env }}
      working_directory: ${{ inputs.working_directory }}

  plan:
    name: "Plan"
    needs: preflight
    uses: aayush01singhal/azure-paas-iac/.github/workflows/tf-plan.yml@main
    with:
      target_env: ${{ inputs.target_env }}
      working_directory: ${{ inputs.working_directory }}
      selected_branch: ${{ inputs.selected_branch }}
      change_ref: ${{ inputs.change_ref }}
      change_reason: ${{ inputs.change_reason }}
      rollback_plan: ${{ inputs.rollback_plan }}


    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  approval:
    name: "Approval gate"
    needs: plan
    uses: ./.github/workflows/approval.gate.yml
    with:
      target_env: ${{ inputs.target_env }}


  
  apply:
    name: "Apply"
    needs: [plan, approval]
    uses: aayush01singhal/azure-paas-iac/.github/workflows/tf-apply.yml@main
    with:
      target_env: ${{ inputs.target_env }}
      working_directory: ${{ inputs.working_directory }}      
      change_ref: ${{ inputs.change_ref }}
      change_reason: ${{ inputs.change_reason }}
      rollback_plan: ${{ inputs.rollback_plan }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


