name: "Workflow to deploy Terraform based infra as code."

run-name: "TF ${{ inputs.target_env }} | ${{ inputs.change_ref }} | @${{ github.actor }} | ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select Environment (uat, sit, production, drhub)"
        required: true
        type: choice
        options: [uat, sit, production, drhub]

      working_directory:
        description: "Terraform config directory path."
        required: true
        default: "."



permissions:
  contents: read
  id-token: write

concurrency:
  group: "tf-${{ inputs.target_env }}-${{ inputs.working_directory }}"
  cancel-in-progress: false

jobs:
  preflight:
    name: "Preflight"
    uses: ./.github/workflows/preflight-checks.yml
    with:
      target_env: ${{ inputs.target_env }}
      working_directory: ${{ inputs.working_directory }}

  plan:
    name: "Plan"
    needs: preflight
    uses: aayush01singhal/azure-paas-iac/.github/workflows/tf-plan.yml@main
    with:
      target_env: ${{ inputs.target_env }}      
      working_directory: ${{ inputs.working_directory }}
      change_ref: ${{ inputs.change_ref }}
      change_reason: ${{ inputs.change_reason }}
      rollback_plan: ${{ inputs.rollback_plan }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  approval:
    name: "Approval gate"
    needs: plan
    uses: ./.github/workflows/approval-gate.yml
    with:
      target_env: ${{ inputs.target_env }}
      change_ref: ${{ inputs.change_ref }}
      change_reason: ${{ inputs.change_reason }}

  apply:
    name: "Apply"
    needs: [plan, approval]
    uses: aayush01singhal/azure-paas-iac/.github/workflows/tf-apply.yml@main
    with:
      target_env: ${{ inputs.target_env }}
      working_directory: ${{ inputs.working_directory }}
      change_ref: ${{ inputs.change_ref }}
    secrets:       
       AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

