name: Preflight checks

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
      working_directory:
        required: true
        type: string
    outputs:
      selected_branch:
        description: "Branch allowed for selected environment"
        value: ${{ jobs.setup.outputs.selected_branch }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: [self-hosted, Windows]
    outputs:
      selected_branch: ${{ steps.branch.outputs.branch }}

    steps:
      - id: branch
        shell: powershell
        run: |
          if ("${{ inputs.target_env }}" -in @("production","drhub")) {
            $branch = "main"
          } else {
            $branch = "${{ inputs.target_env }}"
          }

          "branch=$branch" >> $env:GITHUB_OUTPUT

      - name: Validate branch
        shell: powershell
        run: |
          if ("${{ github.ref_name }}" -ne "${{ steps.branch.outputs.branch }}") {
            throw "Blocked: wrong branch '${{ github.ref_name }}' for environment '${{ inputs.target_env }}'"
          }

      - name: Validate working directory
        shell: powershell
        run: |
          $wd = "${{ inputs.working_directory }}"
          if ($wd.Contains("..") -or $wd.StartsWith("/") -or $wd.StartsWith(".git")) {
            throw "Unsafe working_directory"
          }
