name: Terraform Apply

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

      working_directory:
        required: true
        type: string

      change_ref:
        required: true
        type: string
      
      change_reason:
        required: true
        type: string
      rollback_plan:
        required: true
        type: string


    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init        
        shell: pwsh
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform init -input=false `
              "-backend-config=resource_group_name=rg-tfstate-${{ inputs.target_env }}" `
              "-backend-config=storage_account_name=tfterraform${{ inputs.target_env }}" `
              "-backend-config=container_name=tfstate" `
              "-backend-config=key=${{ inputs.target_env }}/${{ inputs.working_directory }}/terraform.tfstate"
              
      - name: Terraform Apply
        working-directory: ${{ inputs.working_directory }}
        run: terraform apply -auto-approve
