name: Terraform Apply

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

      working_directory:
        required: true
        type: string

      change_ref:
        required: true
        type: string
      
      change_reason:
        required: true
        type: string
      rollback_plan:
        required: true
        type: string


    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ inputs.working_directory }}
        run: terraform apply -auto-approve
